### ISSUE TITLE
how know activity user for collection?

### ISSUE THREAD

**Issue by AbdullahGhanem** [thomastkim/laravel-online-users#1]
if i have user collection

```
$followers = User::whatEver();
```

how can know user activity like 

```
$activityFollowers = $followers->activity();
```

**Comment by thomastkim** [comment]
Did you mean like a twitter feed? Because this package isn't meant to be used like a twitter feed. It's just to show who is currently online. :/

**Comment by thomastkim** [comment]
I'm closing this because of the lack of response.
