### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by HDVinnie** [thomastkim/laravel-online-users#18]
Hello,

I have two questions.

1) How do you stop duplicates? If I log in from two different browsers or devices my name show=s twice in online block.

2) What is guest exactly? My site is private and requires account to access site? yet I see 1000+ guest count?

**Comment by pionas** [comment]
You should edit UserRetriever.php
Replace:
`return  $query->with(['user'])->where('last_activity', '>=', time() - $seconds)->whereNotNull('user_id');`

to:
`return  $query->with(['user'])->where('last_activity', '>=', time() - $seconds)->whereNotNull('user_id')->groupBy('user_id');`
