### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ghost** [thomastkim/laravel-online-users#2]
Hey! When I write this on my site:
// Import at the top
use Activity;

// Find latest users
$activities = Activity::users()->get();

// Loop through and echo user's name
foreach ($activities->users as $user) {
    echo $user->name . '<br>';
}

I became this error:
ErrorException in b75221df64d6887b27b0b34867838817 line 26:
The use statement with non-compound name 'Activity' has no effect (View: /var/www/html/resources/views/startsite/startsite.blade.php)

Can anyone help me? Thanks!

**Comment by thomastkim** [comment]
Short answer: You don't need to add `use Activity;` to your view files. :)

Longer answer: View files aren't in a defined namespace so it's in the "global" namespace. As a result, you don't need to add `use Activity;`. That is only a requirement for classes in a defined namespace like your controllers.

Let me know if you have any other problems.

**Comment by ghost** [comment]
Thanks for your answer! 

I have now remove „use Activity;“.

When I add into my view PHP File:
$activities = Activity::users()->get();

// Loop through and echo user's name
foreach ($activities->users as $user) {
    echo $user->name . '<br>';
}

Than I became also a error:
ErrorException in b75221df64d6887b27b0b34867838817 line 29:
Undefined variable: activities (View: /var/www/html/resources/views/startsite/startsite.blade.php)

Line 29:
foreach ($activities->users as $user) {

**Comment by thomastkim** [comment]
Can you post the contents of your view file just so I can be sure of what's going on?

**Comment by ghost** [comment]
This is my content:

http://pastebin.com/729DtpCP

**Comment by thomastkim** [comment]
That is weird. Can you tell me what you get if you do this?

```
<?php
    $activities = Activity::users()->get();
?>
{{ dd($activities) }}
```

Also, on another note, thanks for pointing out an error in the docs. It should be:

```
foreach ($activities as $activity) {
    echo $activity->user->name;
}
```

I will update the docs when I get home.

**Comment by ghost** [comment]
$activities = Activity::users()->get();
    foreach ($activities as $activity) {
        echo $activity->user->name;
    }

It works =)! Thank you <3!!!

**Comment by thomastkim** [comment]
Awesome! Sorry about that mistake.
