### ISSUE TITLE
User 2x

### ISSUE THREAD

**Issue by ghost** [thomastkim/laravel-online-users#3]
Hey....

I have found a error...

One User is 2x online?

![User 2x](http://fs5.directupload.net/images/151119/le5crrtx.png)

**Comment by thomastkim** [comment]
I think I know what's going on and will push a change in a few hours when I get home.

**Comment by thomastkim** [comment]
This should be fixed now. Just update the package, and you should be good to go!

Let me know if you find anything else. Thanks!

**Comment by ghost** [comment]
Thanks for you help!

Now, I have install new Laravel and you package and I have this error:
SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'sessions' (SQL: select sessions.\* from `site_sessions` left join `site_sessions` as `site_s2` on `site_sessions`.`user_id` = `site_s2`.`user_id` and sessions.last_activity < s2.last_activity where `site_sessions`.`last_activity` >= 1448011548 and `site_sessions`.`user_id` is not null and `site_s2`.`user_id` is null) (View: /var/www/html/resources/views/layouts/default.blade.php) (View: /var/www/html/resources/views/layouts/default.blade.php)

In default.blade.php:
<?php
$users = Activity::users(10)->count();
$guests = Activity::guests(10)->count();
$count = $users + $guests;
$activities = Activity::users()->get();
foreach ($activities as $activity) {
    echo ''.$activity->user->name.'<br>';
}
?>

**Comment by thomastkim** [comment]
Ah, I see. I just pushed a fix to allow for table prefixes. :+1:

**Comment by ghost** [comment]
Thanks for you help!!! Can you say me, when you have fix them?

**Comment by thomastkim** [comment]
Did the latest update not fix it for you?

**Comment by ghost** [comment]
No... Just have a lock:

![Session Error](http://fs5.directupload.net/images/151123/za3je22q.png)

**Comment by thomastkim** [comment]
In your `composer.lock` file, if you look for "kim/activity", can you tell me what version number you see?

**Comment by ghost** [comment]
"version": "1.0.1"

**Comment by ghost** [comment]
Ohh... I have the error... My system haven't update the script. Now, thats function. Thanks for your support!

**Comment by thomastkim** [comment]
Awesome. Does that mean the update fixed your problem? :)
