### ISSUE TITLE
Limit number of authed users

### ISSUE THREAD

**Issue by chaibialaa** [thomastkim/laravel-online-users#5]
Hello,

Is there any way to limit the number of Authed users that we will show ? There is the foreach but can we limit the get() to for exemple 5 users ?

Thank you

**Comment by thomastkim** [comment]
Yes, you can. You can use any Eloquent/Query builder methods. So for example, lets say you are currently doing this to get all active sessions:

```
Activity::users()->get();
```

You can use the laravel's `limit` method to limit the results. So this will only retrieve 5:

```
Activity::users()->limit(5)->get();
```
