### ISSUE TITLE
No migration file?

### ISSUE THREAD

**Issue by joshharington** [thomastkim/laravel-online-users#8]
I have followed the instructions, but when trying to call the migrate function for the sessions table, it just says 'nothing to migrate'. Running Laravel 5.2.

So when trying to use it at all, the site is down because the 'sessions' table is non-existent. Any ideas?

**Comment by achaynes21** [comment]
@joshharington I have the same problem but I tried this and it work:
``You may use the session:table Artisan command to generate this migration for you!

php artisan session:table

composer dump-autoload

php artisan migrate``

**Comment by thomastkim** [comment]
@joshharington Did you run `php artisan session:table` before running `php artisan migrate`?

**Comment by joshharington** [comment]
@thomastkim  yes I did

**Comment by thomastkim** [comment]
That's weird. These commands are a part of Laravel's core and should work out-of-the-box.

If you open up your `database/migrations` folder, you should see something like this (where the X's represent the time when you ran the command):

```
2016_XX_XX_XXXXXX_create_sessions_table.php
```

If that does exist and it's still not working, try running `composer dump-autoload` before you run `php artisan migrate`.

**Comment by 2Fwebd** [comment]
Same issue here. No migration file ... :/

**Comment by joshharington** [comment]
Still nothing. I tried `composer dump-autoload`

**Comment by thomastkim** [comment]
I fixed an error with the readme file that might have been causing some confusion.

If `php artisan session:table` is not working for you guys, please ask the Laravel forum / community. That command is not a part of this package but actually a part of Laravel's core.
