### ISSUE TITLE
Breaks in latest Laravel 5.1 update

### ISSUE THREAD

**Issue by devdurbs** [thomastkim/laravel-online-users#9]
Getting this error after updating to Laravel framework 5.1.40

Missing argument 3 for Illuminate\Session\DatabaseSessionHandler::__construct(), called in D:\wamp\www\b4d\vendor\kim\activity\src\Kim\Activity\ActivityServiceProvider.php on line 50 and defined

**Comment by thomastkim** [comment]
Hey @devdurbs 

Thanks for bringing up this issue. Looks like there were some breaking changes in the most recent version of L5.1. I've pushed an update so just run `composer update`, and it should resolve this issue!

**Comment by devdurbs** [comment]
Perfect, thanks
